### ISSUE TITLE
manpages: source vs 'compiled' pages

### ISSUE THREAD

**Issue by aytchell** [cmusatyalab/coda-doc#1]
I read https://github.com/cmusatyalab/coda/issues/14 and what I understood is this:
 * this repository contains the sgml source code of all the coda-related manpages (in a probably outdated version)
 * The sqml files (DocBook 4.x) had been converted to xml (DocBook 5.0) and updated to reflect changes in the system
 * The coda repository https://github.com/cmusatyalab/coda contains the 'transpiled' nroff/groff versions of the manpages (the updated versions)
 * The xml source code of the nroff/groff versions is lost somewhere

I'd like to find out more about the coda filesystem and in the process of doing so I think I can convert the old sgml files to DocBook 5.0 xml files and then update the contents to match the nroff/groff versions (followed by a pull request to the coda-doc repository). 

Does this task make any sense or is there already some other work going on?

Best regards
Hannes

**Comment by jaharkes** [comment]
Close, the source here is not DocBook 4, but linuxdoc-sgml and there is only the old sgml-tools that can convert it afaik. I'm on the fence if it is worth converting to DocBook 5 xml.

I tried a recent version of pandoc and it got a man page -> markdown conversion that gets it 90% right. With a few tweaks to the markdown it was able to convert back to a man page that looked identical to the original.

Yes, markdown loses a lot of the expressiveness of DocBook, however it is infinitely easier to work with and with pandoc pretty much all output formats (including DocBook 5) can be generated. And the markdown can be generated starting from the existing[*] documentation.

*: probably still pretty outdated

**Comment by aytchell** [comment]
Hi Jan,

I did some tests with the manpages of **cunlog** (as an example for a rather simple page) and **repair** (complex manpage). I converted the two pages to docbook5, markdown (via **pandoc**) and asciidoc (which is used to build git's manpages):

 * the manpage of **cunlog** is no problem with all three tools. With **repair** things get different:
 * the docbook 5 source for *repair* is both: cumbersome to write and read. The documentation is fine but the tags for day-to-day stuff like 'emphasize word' or 'optional parameter' are simply too long.
 * asciidoc and markdown are easy to read but need some trial and error for special things (like 'continuation of lists' or 'setting header and footer' of the manpage); I think, this is only a problem for the initial setup.
 * they also need some discipline to get a consistent look&feel because the markup is not semantic (like TeX or docbook) but "more direct"
 * markdown vs asciidoc is mostly a matter of taste. From my short tests I have the impression, that asciidoc is a bit more expressive but markdown/pandoc should work for all the pages

I'd suggest that I create markdown/pandoc sources for the "more current" manpages in the coda-repository and fine-tune them so they resemble the checked in groff pages. Then I'll adapt the Makefile and commit this to the coda-doc repository.

One issue remains: There are groff pages in 'coda' without sgml and sgml sources in 'coda-doc' without groff pages. (I don't have a list yet ... I think I can assemble a diff.)

**Comment by jaharkes** [comment]
Nice, I had actually already started going through the tree and converting the existing manpages to pandoc/markdown with the idea that even if we wanted docbook it is easier to get there from markdown than from linuxdoc. I'll commit what I have so far.

As far as the sgml without corresponding groff, from my brief scan those all looked like they were either for a program we no longer carry, or they were renamed to avoid using too generic names like 'merge'.

**Comment by aytchell** [comment]
I sorted the markdown pages you've checked in into the appropriate directories and removed the related sgml file. Then I fixed them so the render correctly. I also added three more pages for things which still seem to be in place (rdsinit, rvmutl and bldvldb.sh).

I pushed it to the branch 'pandoc_manpages' of https://github.com/aytchell/coda-doc

I noticed that there are more manpages in rvm/man/man[13]. All the described functions can be found in the coda repository although I didn't find roff-versions of them. Are they worth to be converted?

**Comment by jaharkes** [comment]
I wasn't sure if moving them into individual directories was all that useful because the section is already part of the name so a makefile could in principle figure out where to place things. But split out, I guess, makes the makefile simpler.

Not sure if it is worth atm. to convert any man3 documentation, aside from Coda, I don't think anyone else actually uses the rvm, rpc2 or lwp libraries. Modern programs that were not originally written over 30 years ago would probably use sqlite, grpc and pthreads.

**Comment by jaharkes** [comment]
I noticed volmunge went from .1 to .8, but I think it should be .1. This is a mistake that came from the coda source side of things. The binary is incorrectly getting installed in sbin instead of bin.

**Comment by aytchell** [comment]
I reordered the changes a bit and pushed them to the new branch 'pandoc_2_manpages' of https://github.com/aytchell/coda-doc

* The markdown pages are now located in .../man (not in man[158]) and corrected so that they produce pages very similar to the checked-in roff pages (the md pages seem to be a bit more up-to-date)
* I changed the Makefiles so that the manpages are compiled to roff and can be installed in the appropriate directory (the man-install part is not really elegant; I didn't find a better solution). I skipped the options for 'install' which changes ownership to root.bin since this causes failures when building with a user account.
* volmunge is in section 1 again
* I deleted all the sgml files which are now superseded by md files to avoid confusion. I'm not sure if this OK for you; it's the last commit so it can be dropped easily.

Any further suggestions? Otherwise I'd create a pull request for this branch (and delete the other one).

**Comment by jaharkes** [comment]
No, i don't think I have anything to add.

**Comment by jaharkes** [comment]
I already merged your changes from the pandoc_2_manpages branch, no need for a pull request.

**Comment by aytchell** [comment]
Thanks
